run:
	pm2 start Monitor.js --no-autorestart --name "Monitor-1" -- 1 4000
	pm2 start Monitor.js --no-autorestart --name "Monitor-2" -- 2 4000
	pm2 start Monitor.js --no-autorestart --name "Monitor-3" -- 3 4000
	pm2 start Monitor.js --no-autorestart --name "Monitor-4" -- 4 4000
	pm2 start Monitor.js --no-autorestart --name "Monitor-5" -- 5 4000
	pm2 start Monitor.js --no-autorestart --name "Monitor-6" -- 6 4000
	pm2 start Monitor.js --no-autorestart --name "Monitor-7" -- 7 4000
	pm2 start bottelegram.js 