run:
	pm2 start bottelegram.js 
	
	pm2 start Monitor.py --name "Monitor-1" -- 1 5000
	pm2 start Monitor.py --name "Monitor-1" -- 2 5000
	pm2 start Monitor.py --name "Monitor-1" -- 3 5000
	pm2 start Monitor.py --name "Monitor-1" -- 4 5000
	pm2 start Monitor.py --name "Monitor-1" -- 5 5000
	pm2 start Monitor.py --name "Monitor-1" -- 6 5000
	pm2 start Monitor.py --name "Monitor-1" -- 7 5000
