run:
	pm2 start bottelegram.js 
	pm2 start Monitor.js --name "Monitor-1" -- 1 5000
	pm2 start Monitor.js --name "Monitor-2" -- 2 5000
	pm2 start Monitor.js --name "Monitor-3" -- 3 5000
	pm2 start Monitor.js --name "Monitor-4" -- 4 5000
	pm2 start Monitor.js --name "Monitor-5" -- 5 5000
	pm2 start Monitor.js --name "Monitor-6" -- 6 5000
	pm2 start Monitor.js --name "Monitor-7" -- 7 5000